openapi: 3.0.0
info:
  title: Dink Derby API
  description: A REST API for managing anglers, derbies, catches, and fishing locations in a fishing competition system.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/anglers:
    post:
      summary: Create a new angler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAngler'
      responses:
        '201':
          description: Angler created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Angler'
  /api/anglers/derby/{id}:
    get:
      summary: Get anglers by derby ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: objectid
      responses:
        '200':
          description: Anglers retrieved by derby
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Angler'
        '400':
          description: Invalid derby ID
        '404':
          description: No anglers found for the given derby ID
  /api/anglers/{id}:
    get:
      summary: Get angler by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: objectid
      responses:
        '200':
          description: Angler details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Angler'
    put:
      summary: Update a angler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAngler'
      responses:
        '200':
          description: Angler updated
    delete:
      summary: Delete a angler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Angler deleted
  /api/derbies:
    post:
      summary: Create a new derby
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Derby'
      responses:
        '201':
          description: Derby created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Derby'
        '500':
          description: Internal server error
  /api/derby/{id}:
    get:
      summary: Get derby by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: objectid
      responses:
        '200':
          description: Derby details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Derby'
        '400':
          description: Invalid derby ID
        '404':
          description: Derby not found
        '500':
          description: Internal server error
  /api/derbies/angler/{id}:
    get:
      summary: Get derbies by angler ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: objectid
          description: The ID of the angler
      responses:
        '200':
          description: A list of derbies the angler is participating in
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Derby'
        '400':
          description: Invalid angler ID
        '404':
          description: No derbies found for the given angler ID
        '500':
          description: Internal server error



    get:
      summary: Get derbies by angler ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the angler
      responses:
        '200':
          description: A list of derbies the angler is participating in
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Derby'
        '500':
          description: Internal server error

components:
  schemas:
    Angler:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
    NewAngler:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    Derby:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
    NewDerby:
      type: object
      properties:
        name:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
    Catch:
      type: object
      properties:
        _id:
          type: string
        species:
          type: string
        weight:
          type: number
        location:
          $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        location_id:
          type: string
        name:
          type: string
